#!/usr/bin/env bash
# Use the native MacOS X/macOS mechanisms to perform forward and reverse DNS lookups
# gurple@mac.com
# Version: 2016090131105 - Initial
# Version: 201808071148 - Updated to perform reverse lookups.

STAT=1
if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] ; then
	OIFS=$IFS
	IFS='.'
	ip=($1)
	IFS=$OIFS
	[[ ${ip[0]} -le 255 && ${ip[1]} -le 255 && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]] || echo "Invalid IPv4 Address" && exit "$STAT"
	LOOKUPTYPE=IPv4
	LOOKUPRESULT="$(dscacheutil -q host -a ip_address "$1")"
elif [[ $1 =~ ^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$ ]] ; then
	LOOKUPTYPE=IPv6
	LOOKUPRESULT="$(dscacheutil -q host -a ip_address "$1")"
elif [ -z "$LOOKUPTYPE" ] ; then
	LOOKUPTYPE=HOSTNAME
	LOOKUPRESULT="$(dscacheutil -q host -a name "$1")"
fi

if [ -z "$LOOKUPRESULT" ] ; then
	exit "$STAT"
else
	echo "$LOOKUPRESULT"
	STAT=0
	exit "$STAT"
fi
